Improving gha's to make them consistent (#3099)
* Improving gha's to make them consistent

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Changed back the spark script file names

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* fix the structure of the end to end integration to keep install part and test part seperate

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Fixed the pod timming issue

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Added unauthorized test for model registry

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* corrected the message

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Updated the title of gha's as suggested

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Updated the titles of workflows as suggested

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Fixed the lint errors

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>

* Update kserve_m2m_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Delete .github/workflows/notebook_controller_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update spark_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update ray_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update pipeline_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update pipeline_swfs_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update pipeline_run_from_notebook.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update notebook_controller_m2m_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update model_registry_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update kserve_m2m_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Rename notebook_controller_m2m_test.yaml to notebook_controller_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Rename kserve_m2m_test.yaml to kserve_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update full_kubeflow_integration_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update pipeline_swfs_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

* Update pipeline_swfs_test.yaml

Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

---------

Signed-off-by: kunal-511 <yoyokvunal@gmail.com>
Signed-off-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>
Co-authored-by: Julius von Kohout <45896133+juliusvonkohout@users.noreply.github.com>

diff --git a/.github/workflows/full_kubeflow_integration_test.yaml b/.github/workflows/full_kubeflow_integration_test.yaml
--- a/.github/workflows/full_kubeflow_integration_test.yaml
+++ b/.github/workflows/full_kubeflow_integration_test.yaml
@@ -1,4 +1,4 @@
-name: End-to-End Integration Test
+name: Test End-to-End Integration
 on:
   workflow_dispatch:
   push:
@@ -80,10 +80,19 @@ jobs:
       run: ./tests/gh-actions/install_training_operator.sh
 
     - name: Install Knative
-      run: ./tests/gh-actions/install_knative.sh
+      run: ./tests/gh-actions/install_knative-cni.sh
 
     - name: Install KServe
       run: ./tests/gh-actions/install_kserve.sh
+
+    - name: Install Model Registry
+      run: |
+        kustomize build apps/model-registry/upstream/overlays/db | kubectl apply -f -
+        kustomize build apps/model-registry/upstream/options/istio | kubectl apply -f -
+
+    - name: Install Model Registry UI
+      run: |
+        kustomize build apps/model-registry/upstream/options/ui/overlays/istio | kubectl apply -f -
 
     - name: Install Spark
       run: chmod u+x tests/gh-actions/spark_*.sh && ./tests/gh-actions/spark_install.sh
@@ -165,6 +174,42 @@ jobs:
 
     - name: Run Spark Test
       run: chmod u+x tests/gh-actions/spark_*.sh && ./tests/gh-actions/spark_test.sh "${KF_PROFILE}"
+
+    - name: Test Model Registry Deployment
+      run: |
+        kubectl wait --for=condition=available -n kubeflow deployment/model-registry-db --timeout=600s
+        kubectl wait --for=condition=available -n kubeflow deployment/model-registry-deployment --timeout=600s
+
+    - name: Test Model Registry UI Deployment
+      run: kubectl wait --for=condition=available -n kubeflow deployment/model-registry-ui --timeout=600s
+
+    - name: Test Model Registry API
+      run: |
+        export KF_TOKEN="$(kubectl -n $KF_PROFILE create token default-editor)"
+
+        nohup kubectl port-forward svc/model-registry-service -n kubeflow 8082:8080 &
+        sleep 5
+        curl -s -X 'GET' \
+          'http://localhost:8082/api/model_registry/v1alpha3/registered_models?pageSize=100&orderBy=ID&sortOrder=DESC' \
+          -H 'accept: application/json'
+
+        curl -s --fail \
+          "localhost:8080/model-registry/api/v1/model_registry?namespace=${KF_PROFILE}" \
+          -H "Authorization: Bearer ${KF_TOKEN}"
+
+    - name: Test Model Registry API with Unauthorized Token
+      run: |
+        UNAUTHORIZED_TOKEN=$(kubectl -n test-unauthorized create token test-unauthorized || kubectl -n test-unauthorized create token default)
+
+        STATUS_CODE=$(curl -s \
+          --output /dev/stderr --write-out "%{http_code}" \
+          "localhost:8080/model-registry/api/v1/model_registry?namespace=${KF_PROFILE}" \
+          -H "Authorization: Bearer ${UNAUTHORIZED_TOKEN}")
+
+        if test $STATUS_CODE -ne 403; then
+          echo "Error: Unauthorized access was not correctly rejected. Got status code: ${STATUS_CODE}"
+          exit 1
+        fi
 
     - name: Apply Pod Security Standards Baseline
       run: ./tests/gh-actions/enable_baseline_PSS.sh
