Synchronize kubeflow pipelines manifests 2.4.0 (#2953)
* Update kubeflow/pipelines manifests from 2.4.0

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* update the kfp version

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* update metacontroller nly to 2.6.1 and use the kubeflow-edit clusterrole instead of cluster-admin.

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* add checks for metacontroller

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* revert to cluster-admin for now and add more tests.git status

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* more tests

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* more tests

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* more tests

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* more tests

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* more tests

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* more tests

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* try kubeflow-admin instead of cluster-admin

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

* explicit clusterrole

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

---------

Signed-off-by: juliusvonkohout <45896133+juliusvonkohout@users.noreply.github.com>

diff --git a/.github/workflows/pipeline_swfs_test.yaml b/.github/workflows/pipeline_swfs_test.yaml
--- a/.github/workflows/pipeline_swfs_test.yaml
+++ b/.github/workflows/pipeline_swfs_test.yaml
@@ -48,7 +48,32 @@ jobs:
       run: kustomize build common/istio-1-24/kubeflow-istio-resources/base | kubectl apply -f -
 
     - name: Create KF Profile
-      run: kustomize build common/user-namespace/base | kubectl apply -f -
+      run: |
+        kustomize build common/user-namespace/base | kubectl apply -f -
+        sleep 30 # for the metacontroller to create the secret
+
+        METACONTROLLER_POD=$(kubectl get pods -n kubeflow -o json | jq -r '.items[] | select(.metadata.name | startswith("metacontroller")) | .metadata.name')
+        if [[ -z "$METACONTROLLER_POD" ]]; then
+          echo "Error: metacontroller pod not found in kubeflow namespace."
+          exit 1
+        fi
+        kubectl logs -n kubeflow "$METACONTROLLER_POD"
+
+        PIPELINES_PROFILE_CONTROLLER_POD=$(kubectl get pods -n kubeflow -o json | jq -r '.items[] | select(.metadata.name | startswith("kubeflow-pipelines-profile-controller")) | .metadata.name')
+        if [[ -z "$PIPELINES_PROFILE_CONTROLLER_POD" ]]; then
+          echo "Error: kubeflow-pipelines-profile-controller pod not found in kubeflow namespace."
+          exit 1
+        fi
+        kubectl logs -n kubeflow "$PIPELINES_PROFILE_CONTROLLER_POD"
+
+        KF_PROFILE=kubeflow-user-example-com
+        kubectl -n $KF_PROFILE get pods,configmaps,secrets
+
+        if ! kubectl get secret mlpipeline-minio-artifact -n $KF_PROFILE > /dev/null 2>&1; then
+          echo "Error: Secret mlpipeline-minio-artifact not found in namespace $KF_PROFILE"
+          exit 1
+        fi
+        kubectl get secret mlpipeline-minio-artifact -n "$KF_PROFILE" -o json | jq -r '.data | keys[] as $k | "\($k): \(. | .[$k] | @base64d)"' | tr '\n' ' '
 
     - name: Install seaweedfs
       run: |
