Proper message display when no Yaml files chnaged in the PR
Signed-off-by: hansinikarunarathne <107214435+hansinikarunarathne@users.noreply.github.com>

diff --git a/.github/workflows/yaml_formatter.yaml b/.github/workflows/yaml_formatter.yaml
--- a/.github/workflows/yaml_formatter.yaml
+++ b/.github/workflows/yaml_formatter.yaml
@@ -43,17 +43,26 @@ jobs:
       run: git fetch origin master
     
     - name: Set up changed files
+      id: changed_files
       run: |
         git diff --name-only origin/master...HEAD | grep -E '^common/.*\.ya?ml$|^example/.*\.ya?ml$' > changed_files_in_PR.txt || true
+        if [ ! -s changed_files_in_PR.txt ]; then
+          echo "No YAML files have changed in this PR." > changed_files_in_PR.txt
+        fi
     
     - name: Display changed files
       run: cat changed_files_in_PR.txt
 
     - name: Run yamllint on changed files
       run: |
-        chmod +x ./run_yamllint.sh
-        ./run_yamllint.sh
+        if [ -s changed_files_in_PR.txt ]; then
+          cat changed_files_in_PR.txt | xargs yamllint
+          if [ $? -eq 0 ]; then
+            echo "No YAML style errors found in the changed files."
+          else
+            echo "YAML style errors were found."
+          fi
+        else
+          echo "No YAML files have changed in this PR."
+        fi
       shell: bash
-
-      
-
